# fly.toml app configuration file generated for kingdomscout-backend on 2026-02-06T12:02:06-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kingdomscout-backend'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3001'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
